name: Prettier Format Check

on: [ push, pull_request ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Prettier check
      run: npx prettier --check .
